export const productsData = [
  {
    id: 1,
    productName: "Piatos",
    category: "Chips",
    subCategory: "Chips",
    unit: 1,
    stock: 5000,
    minimumQty: 100,
    quantity: 1000,
    description: "Product Description 1",
    tax: "5%",
    discountType: 1,
    price: 10,
    status: "Active",
    image: "Product Image 1",
  },
  {
    id: 2,
    productName: "Bangus",
    category: "Fish",
    subCategory: "Fish",
    unit: 1,
    stock: 5000,
    minimumQty: 100,
    quantity: 1000,
    description: "Product Description 2",
    tax: "5%",
    discountType: 1,
    price: 10,
    status: "Active",
    image: "Product Image 2",
  },
  {
    id: 3,
    productName: "Maling",
    category: "Canned",
    subCategory: "Canned",
    unit: 1,
    stock: 5000,
    minimumQty: 100,
    quantity: 1000,
    description: "Product Description 3",
    tax: "5%",
    discountType: 1,
    price: 10,
    status: "Active",
    image: "Product Image 3",
  },
];
